apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      name: indexer
      labels:
        app: indexer
    spec:
      containers:
        - name: indexer
          image: theocerutti/kubi-indexer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_URI
              value: http://elastic-search:9200
            - name: ELASTICSEARCH_USER
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-search-password
                  key: ELASTIC_PASSWORD
            - name: AMQP_URI
              value: amqp://guest:guest@rabbitmq:5672
      restartPolicy: Always