apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
        - name: database-migration-job
          image: theocerutti/kubi-back:latest
          imagePullPolicy: IfNotPresent
          args:
            - php
            - artisan
            - migrate
      restartPolicy: Never
