apiVersion: v1
kind: Service
metadata:
  name: elastic-search
spec:
  selector:
    app: elastic-search
  ports:
    - port: 9200
      targetPort: 9200
      name: http
    - port: 9300
      targetPort: 9300
      name: transport
  type: NodePort
