apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_management, rabbitmq_mqtt].
  # TODO: use helm or something else to use secret interpolation here
  rabbitmq.conf: |
    loopback_users.guest = false
    default_user = guest
    default_pass = guest
    management.tcp.ip = 0.0.0.0
