apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.1-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: amqp
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
            - name: config
              mountPath: /etc/rabbitmq
      restartPolicy: Always
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
        - name: config
          configMap:
            name: rabbitmq-config
            defaultMode: 0755
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
              - key: enabled_plugins
                path: enabled_plugins
  selector:
    matchLabels:
      app: rabbitmq
