apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage-volume
            - mountPath: /etc/grafana/
              name: grafana-config-volume
      volumes:
        - name: grafana-storage-volume
          emptyDir: { }
        - name: grafana-config-volume
          configMap:
            defaultMode: 420
            name: grafana
            items:
              - key: grafana.ini
                path: grafana.ini
              - key: datasource.yml
                path: provisioning/datasources/datasource.yml
      restartPolicy: Always
